import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Sidebar from '@/components/Sidebar'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Calcu - Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "grainy",
inter.className
          )}>
<div className='flex flex-row gap-2'>
            <Sidebar />
            {children}
</div>
            </body>
    </html>
  );
}
